export const constants = {
    // general
    DATA_ID_ATTRIBUTE: 'data-flowforge-id',
    LOCAL_STORAGE_NAMESPACE: 'flowforge',
    // api
    API_QUERY_TIMEOUT_MS: 60000,
    // popup
    EXAMPLES_MAX_ITEMS: 5,
    EXAMPLES_MAX_QUESTION_LENGTH: 50,
    // extractors
    CONTENT_ELEMENTS_LIMIT: 250,
    INTERACTIVE_ELEMENTS_LIMIT: 150,
    // highlighter
    HIGHLIGHT_DEFAULT_DURATION_MS: 8000,
    HIGHLIGHT_MOUNT_DELAY_MS: 150,
    HIGHLIGHT_UNMOUNT_DELAY_MS: 150,
    HIGHLIGHT_OVERLAY_PADDING: 6,
    HIGHLIGHT_LABEL_MIN_WIDTH: 160,
    HIGHLIGHT_LABEL_MAX_WIDTH: 400,
};
