export const constants = {
    // general
    DATA_ID_ATTRIBUTE: 'data-flowforge-id',
    HISTORY_STORAGE_NAMESPACE: 'flowforge-history',
    // api
    API_QUERY_TIMEOUT_MS: 60000,
    // popup
    EXAMPLES_MAX_ITEMS: 5,
    EXAMPLES_MAX_QUESTION_LENGTH: 40,
    // extractor
    CONTENT_ELEMENTS_LIMIT: 250,
    INTERACTIVE_ELEMENTS_LIMIT: 150,
    CONTENT_MIN_TEXT_LENGTH: 10,
    CONTEXT_SECTION_NAME_HOIST_DEPTH: 5,
    CONTEXT_SECTION_NAME_MIN_LENGTH: 5,
    CONTEXT_SECTION_NAME_MAX_LENGTH: 30,
    CONTEXT_PATH_HOIST_DEPTH: 6,
    CONTEXT_PATH_ITEMS_LIMIT: 4,
    // highlighter
    HIGHLIGHT_DEFAULT_DURATION_MS: 8000,
    HIGHLIGHT_MOUNT_DELAY_MS: 150,
    HIGHLIGHT_UNMOUNT_DELAY_MS: 150,
    HIGHLIGHT_OVERLAY_PADDING: 6,
    HIGHLIGHT_LABEL_MIN_WIDTH: 160,
    HIGHLIGHT_LABEL_MAX_WIDTH: 400,
};
